services:
  mariadb:
    build: ./requirements/mariadb
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped

  wordpress:
    build: ./requirements/wordpress
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
      - wp_admin_password
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html:rw
    depends_on:
      - mariadb
    restart: unless-stopped

  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html:rw
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - wordpress
    networks:
      - inception
    restart: unless-stopped

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt

volumes:
  wordpress:
    name : wordpress
    driver: local
    driver_opts:
      type: none
      device: /home/amugisha/data/wp
      o: bind
  mariadb:
    name : mariadb
    driver: local
    driver_opts:
      type: none
      device: /home/amugisha/data/mariadb
      o: bind

networks:
  inception:
    name: inception
    driver: bridge
